Repository open-research/sumatra, pull requests merged in 2025-04, with the labels that each got.

#392 Fix: Replace literal tests by equal tests.
  sumatra/projects.py
  sumatra/versioncontrol/_git.py
Labels: bug

#393 Fix: Remove some local cache files
  test/example_repositories/bazaar/bzr/checkout/conflicts
  test/example_repositories/mercurial/hg/branch.cache
  test/example_repositories/mercurial/hg/store/data/subpackage/____init____.py.i
  test/example_repositories/subversion/locks/db-logs.lock
  test/example_repositories/subversion/locks/db.lock
Labels: task

#400 Enh: Allow using '~' in projects file to indicate home directory.
  sumatra/datastore/filesystem.py
  sumatra/launch.py
  sumatra/projects.py
  sumatra/recordstore/django_store/__init__.py
  sumatra/recordstore/shelve_store.py
  sumatra/versioncontrol/base.py
Labels: enhancement

#404 Support for Django v4 and v5
  README.rst
  ci/requirements.txt
  setup.py
  sumatra/commands.py
  sumatra/core.py
  sumatra/datastore/filesystem.py
  sumatra/formatting/__init__.py
  sumatra/pfi.py
  sumatra/projects.py
  sumatra/records.py
  sumatra/recordstore/django_store/__init__.py
  sumatra/recordstore/django_store/migrations/0001_initial.py
  sumatra/recordstore/django_store/migrations/__init__.py
  sumatra/recordstore/serialization.py
  sumatra/recordstore/shelve_store.py
  sumatra/web/templatetags/filters.py
  sumatra/web/views.py
  test/system/fixtures/Dockerfile.postgres
  test/system/test_http_store.py
  test/system/test_ircr.py
  test/system/test_postgres.py
  test/system/utils.py
  test/unittests/test_datastore.py
  test/unittests/test_formatting.py
  test/unittests/test_projects.py
  test/unittests/test_recordstore.py
  tools/export.py
Labels: enhancement, smtweb, web module, recordstore module

#405 Make Django, httplib2, jinja2, docutils optional
  .github/workflows/tests.yml
  .gitignore
  ci/requirements-min.txt
  ci/requirements-test.txt
  ci/requirements.txt
  sumatra/formatting/__init__.py
  sumatra/projects.py
  sumatra/recordstore/__init__.py
  sumatra/recordstore/base.py
  sumatra/recordstore/django_store/__init__.py
  sumatra/recordstore/shelve_store.py
  sumatra/web/views.py
  test/system/test_http_store.py
  test/system/test_ircr.py
  test/system/test_postgres.py
  test/system/test_webdav.py
  test/system/test_webui.py
  test/system/utils.py
  test/unittests/test_commands.py
  test/unittests/test_formatting.py
  test/unittests/test_projects.py
  test/unittests/test_publishing.py
  test/unittests/test_recordstore.py
  test/unittests/test_versioncontrol.py
  test/unittests/test_web.py
  tox.ini
Labels: enhancement

#372 Fix a different in interface between NTParameterSet and the other ParameterSet classes
  sumatra/parameters.py
  test/unittests/test_parameters.py
Labels: parameters module

#388 Add support for MySQL and MariaDB
  sumatra/recordstore/django_store/__init__.py
  test/system/fixtures/Dockerfile.mysql
  test/system/test_mysql.py
Labels: enhancement, recordstore module

#408 Internalise code for tag management
  LICENSE
  README.rst
  doc/authors.txt
  pyproject.toml
  sumatra/recordstore/django_store/__init__.py
  sumatra/recordstore/django_store/migrations/0001_initial.py
  sumatra/recordstore/django_store/migrations/0002_tag_taggeditem.py
  sumatra/recordstore/django_store/models.py
  sumatra/recordstore/django_store/tagging.py
  sumatra/recordstore/django_store/tagging_utils.py
  sumatra/web/views.py
Labels: task
